# Site
repository: https://mimeugene.github.io/
# favicon: images/favicon.ico

# Personal info
name: Eugene Mim
title: Computer Programmer
email: mim.eugene@gmail.com
website: https://mimeugene.github.io/

# Social links
github_username:  mimeugene
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: eugene-mim-248a0931
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Passionate, driven programmer with a track record of commended performance with projects in various frameworks. Well versed in all phases of the software development cycle.
  I am most skilled in: <mark>Python</mark> and <mark>Javascript</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in programming and IT, some of my other interests and hobbies are:
   - Game development
   - Electronics tinkerer
   - Surfing

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
